package com.reliefsync.model.enums;

public enum Permission {
  MANAGE_USERS,
  VIEW_DISASTERS,
  MANAGE_DISASTERS,
  VIEW_AFFECTED_AREAS,
  MANAGE_AFFECTED_AREAS,
  VIEW_RELIEF_CENTERS,
  MANAGE_RELIEF_CENTERS,
  VIEW_RESOURCES,
  MANAGE_RESOURCES,
  VIEW_INVENTORY,
  MANAGE_INVENTORY,
  CREATE_RELIEF_REQUEST,
  VERIFY_RELIEF_REQUEST,
  VIEW_ALLOCATIONS,
  MANAGE_ALLOCATIONS,
  VIEW_VEHICLES,
  MANAGE_VEHICLES,
  VIEW_DISPATCHES,
  MANAGE_DISPATCHES,
  VIEW_REPORTS
}
